### PR TITLE
Modernize .travis.yml and fix beginswith->startswith deprecation

### PR DESCRIPTION
**Pull request by timholy**
Not sure if I've got the syntax correct, but we'll see. This is more complicated than is typical, because:
- I want to submit to Coveralls only from the nightly build, since I want to use features like `--inline=no`
- I am running the tests for two packages (HDF5 and JLDArchives) in a single session, to make sure the coverage files include the tests of both

### CODE REVIEW

**Comment by timholy** [comment]
Looks like the syntax isn't correct. CC @ninjin, @tkelman, any tips here?

**Comment by tkelman** [comment]
I'll have to check those docs I wrote, but I think you want to change `$JULIAVERSION` to `$TRAVIS_JULIA_VERSION`

**Comment by timholy** [comment]
It's also complaining
```
/home/travis/build.sh: line 41: [: =: unary operator expected
```
Is using `=` for comparisons correct?

**Comment by tkelman** [comment]
Pretty sure that's just a bash symptom of trying to do `if [ $JULIAVERSION = "nightly" ]` when `JULIAVERSION` is not defined, since it has no quotes around it.

**Comment by timholy** [comment]
Indeed, that did the trick. Thanks!

(And wow, those tests run much more quickly with the modern script.)

**Comment by tkelman** [comment]
> And wow, those tests run much more quickly with the modern script

That part was a big surprise to me. Here I thought apt-get was a reasonably fast way to get a binary onto a machine but apparently not. You don't have an education account at Travis do you? I think those might route to the new docker-based workers if you don't use `sudo` at all. Or you might need to explicitly ask for that with `sudo: false` in your `.travis.yml` file, not sure. Supposedly those are even faster.

**Comment by timholy** [comment]
Whew, looks like I finally ran out of ways to make syntax errors.

Turning on these various settings made a big difference in the (new) coverage percentages: 59% with the old travis script and 72% with the new. Most of that probably comes from combining the results of HDF5 & JLDArchive tests, but looking at the results, there's some real benefit to turning off the inlining (functions I _knew_ were tested, indeed are).

**Comment by tkelman** [comment]
yeah that makes sense, I misread your Julia pull request the first time around

**Comment by romainFr** [comment]
It seems that the deprecation fix isn't compatible with 0.3.4 (startswith is not defined there), but 0.3.4 users are likely to want to use the checkout version of HDF5 because of #198.

**Comment by simonster** [comment]
@romainFr I believe this should work if you update Compat.jl.

**Comment by timholy** [comment]
yes, just do `Pkg.update()`.

**Pull request merged**
