### PR TITLE
fix dict syntax in build.jl

### PR DESCRIPTION
**Pull request by rened**

### CODE REVIEW

**Comment by simonster** [comment]
This doesn't appear to work. The Travis builds fail with:

```
LoadError: UndefVarError: @compat not defined

while loading /home/travis/.julia/v0.4/HDF5/deps/build.jl, in expression starting on line 25
```

@tkelman, you have any idea what to do about this deprecation warning? I'll work on the concatenation warnings.

**Comment by tkelman** [comment]
Dunno, I think people have just been living with this one.

**Comment by rened** [comment]
I tried to reverse the order of `@compat` and `@BinDeps.install` - it seems to work now.

**Comment by timholy** [comment]
Very nice, thanks!

**Pull request merged**
